import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "keen-slider/keen-slider.min.css";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper"; 
import { Toaster } from 'sonner'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Revelo.in",
  description: "Generated by create next app",
    icons: {
    icon: "/favicon.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#111111] text-white`}
      >
        <SessionWrapper>
          {children}
           <Toaster position="top-right" richColors />
        </SessionWrapper>
        
      </body>
    </html>
  );
}
